const assert = require('node:assert/strict');
const RoomManager = require('../src/RoomManager');
const Tutorial = require('../src/Tutorial');
const rooms = new RoomManager();
const packets = [];
const tutorial = new Tutorial(rooms, (ws, type, data) => packets.push({ type, data: structuredClone(data) }));
const ws = { clientId: 'learner' };
const room = tutorial.start(ws);
const action = (type, data) => tutorial.handle(ws, type, data);
const ack = () => action('tutorial_ack', { revision: room.tutorial.revision });
const step = name => assert.equal(room.tutorial.step, name);
const cards = () => room.players.flatMap(p => p.hand).concat(room.kitty).map(c => c.id);
assert.equal(new Set(cards()).size, 53);
assert.ok(room.players.every(p => p.hand.length === 10));
const firstHands = room.players.map(p => p.hand.map(c => c.id));
step('intro');
action('play_card', { cardId: 'S_A' }); // cannot bypass a lesson
assert.equal(room.tableCards.length, 0);
action('tutorial_ack', { revision: -1 });
step('intro');
ack(); step('strength');
assert.equal(room.tableCards.length, 0);
action('play_card', { cardId: 'S_A' });
assert.equal(room.tableCards.length, 0);
ack(); step('team');
assert.equal(room.tableCards.length, 0);
ack(); step('follow');
assert.equal(room.tableCards.length, 1);
ack(); step('mighty');
assert.equal(room.tableCards.length, 4);
assert.equal(room.friendRevealed, false);
assert.equal(room.friendClientId, ws.clientId);
assert.equal(rooms.publicState(room, ws.clientId).friendClientId, null);
assert.ok(room.players[0].hand.some(c => c.id === room.friendCardId));
ack();
action('play_card', { cardId: 'C_3' }); // wrong legal card cannot derail the script
assert.equal(room.tableCards.length, 4);
action('play_card', { cardId: 'S_A' }); step('reveal');
assert.equal(room.friendRevealed, true);
for (const player of room.players) {
  const state = rooms.publicState(room, player.clientId);
  assert.equal(state.friendRevealed, true);
  assert.equal(state.friendClientId, ws.clientId);
}
assert.ok(!room.players[0].hand.some(c => c.id === room.friendCardId));
assert.equal(room.lastTrickWinner.clientId, ws.clientId);
ack(); step('call'); ack();
action('play_card', { cardId: 'C_3', activateJokerCall: false });
assert.equal(room.players[0].hand.length, 9);
action('play_card', { cardId: 'C_3', activateJokerCall: true }); step('round_end');
assert.equal(room.tableCards[2].card.id, 'JOKER');
assert.equal(room.lastTrickWinner.clientId, room.players[1].clientId);
ack(); step('bid');
assert.equal(new Set(cards()).size, 53);
ack();
action('bid', { targetScore: 13, trumpSuit: 'SPADE' });
assert.equal(room.status, 'bidding');
action('bid', { targetScore: 13, trumpSuit: 'HEART' }); step('discard');
assert.equal(room.players[0].hand.length, 13);
ack();
action('discard_kitty', { cardIds: ['S_2','D_2','missing'] });
assert.equal(room.players[0].hand.length, 13);
action('discard_kitty', { cardIds: ['S_2','D_2','C_2'] }); step('friend');
assert.equal(room.players[0].hand.length, 10);
ack(); action('choose_friend', { friendCardId: 'S_A' }); step('lead');
ack(); action('play_card', { cardId: 'H_A' }); step('complete');
assert.equal(room.lastTrickWinner.clientId, ws.clientId);
assert.equal(room.trickHistory.length, 1);
assert.equal(room.players[0].hand.length, 9);
ack(); step('complete');
action('tutorial_restart'); step('intro');
assert.deepEqual(room.players.map(p => p.hand.map(c => c.id)), firstHands);
tutorial.sync(room);
assert.equal(packets.at(-1).type, 'tutorial_state');
action('leave_room');
assert.equal(rooms.getRoom(room.roomId), undefined);
assert.equal(ws.roomId, null);
console.log('Tutorial: two scripted rounds, lesson barriers, invalid inputs, restart and exit passed.');
